# Generated by Django 3.0.6 on 2020-05-24 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=128)),
                ('last_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Constituency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.PositiveIntegerField()),
                ('name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.CreateModel(
            name='ElectionPartyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.Election')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('party_name', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_hash', models.CharField(max_length=512)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.Election')),
            ],
        ),
        migrations.CreateModel(
            name='PartyVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_votes', models.PositiveIntegerField(default=0)),
                ('elected_party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.ElectionPartyList')),
            ],
        ),
        migrations.AddField(
            model_name='electionpartylist',
            name='party',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.Party'),
        ),
        migrations.CreateModel(
            name='ElectionCandidateList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.Candidate')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.Election')),
            ],
        ),
        migrations.CreateModel(
            name='ElectionArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('constituency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.Constituency')),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='election.Election')),
            ],
        ),
        migrations.CreateModel(
            name='CandidateVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_votes', models.PositiveIntegerField(default=0)),
                ('elected_candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='election.ElectionCandidateList')),
            ],
        ),
        migrations.AddField(
            model_name='candidate',
            name='party_affiliation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='election.Party'),
        ),
    ]
