# Generated by Django 3.0.6 on 2020-05-24 15:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='duration',
        ),
        migrations.AddField(
            model_name='election',
            name='endDateTiem',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='election',
            name='startDateTime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
