# Generated by Django 3.0.6 on 2020-05-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('election', '0002_auto_20200524_1508'),
    ]

    operations = [
        migrations.RenameField(
            model_name='election',
            old_name='endDateTiem',
            new_name='endDateTime',
        ),
    ]
